// test/skills-build-mode-overview.test.js
//
// Phase 7 BUILD-01: locks frontmatter validity, line-count ceiling, catalogue
// enumeration, predicate phrase presence, response-mode cross-references, and
// in-file forbidden-fingerprint scan for the build-mode voice anchor.
// Defence-in-depth: the package-wide lint-grep test (Phase 9) covers every
// shipped file; this test pins the keystone earlier.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parseFrontmatter } from '../lib/frontmatter.js';

const here = dirname(fileURLToPath(import.meta.url));
const FILE = join(here, '..', 'skills', 'build-mode-overview.md');

const RESPONSE_MODE_SKILLS = [
  'philosophical-preamble',
  'architecture-astronaut',
  'legacy-language-supremacy',
  'build-system-from-scratch',
  'testing-by-formal-proof',
];

const BUILD_MODE_CHILDREN = [
  'build-compiler-from-scratch.md',
  'build-json-parser-from-scratch.md',
  'build-http-stack-from-scratch.md',
  'build-build-system-from-scratch.md',
  'build-project-tree-template.md',
  'build-philosophical-preamble.md',
  'build-free-monad-encoder.md',
  'build-dsl-grammar.md',
  'build-coq-proof-stub.md',
  'build-forth-bootstrap.md',
  'build-abstract-factory-of-factories.md',
  'build-monad-transformer-stack.md',
];

const FORBIDDEN = /\b(claude|anthropic|openai|codex|copilot|gemini|aider|cline|sonnet|opus|haiku|llm|assistant)\b|\b(AI|agent)\b|cursor[ -]?ai|generated by|authored by ai/i;

test('build-mode-overview: file exists and parses with strict 3-key frontmatter', async () => {
  const src = await readFile(FILE, 'utf8');
  const { data, body } = parseFrontmatter(src);
  assert.equal(data.name, 'build-mode-overview');
  assert.ok(data.description && data.description.length > 0);
  assert.ok(data.when_to_use && data.when_to_use.length > 0);
  assert.equal(Object.keys(data).length, 3, 'frontmatter must have exactly 3 keys');
  assert.ok(body.length > 100, 'body must be substantive');
});

test('build-mode-overview: total line-count is 80..200 (existing skill convention)', async () => {
  const src = await readFile(FILE, 'utf8');
  const lines = src.split('\n').length;
  assert.ok(lines >= 80, `expected >= 80 lines, got ${lines}`);
  assert.ok(lines <= 200, `expected <= 200 lines, got ${lines}`);
});

test('build-mode-overview: cross-references at least 5 response-mode skills by name', async () => {
  const src = await readFile(FILE, 'utf8');
  const hits = RESPONSE_MODE_SKILLS.filter((name) => src.includes(name));
  assert.ok(hits.length >= 5, `expected >= 5 response-mode cross-refs, got ${hits.length}: ${hits.join(',')}`);
});

test('build-mode-overview: enumerates all 12 build-* child skill filenames', async () => {
  const src = await readFile(FILE, 'utf8');
  const missing = BUILD_MODE_CHILDREN.filter((f) => !src.includes(f));
  assert.deepEqual(missing, [], `missing child enumerations: ${missing.join(', ')}`);
});

test('build-mode-overview: contains the build-mode predicate phrase', async () => {
  const src = await readFile(FILE, 'utf8');
  assert.ok(
    src.includes('When the user asks you to produce'),
    'predicate phrase missing — host must be told when build-mode applies',
  );
});

test('build-mode-overview: contains the catalogue section heading', async () => {
  const src = await readFile(FILE, 'utf8');
  assert.match(src, /^## The Build-Mode Catalogue/m);
});

test('build-mode-overview: zero forbidden-fingerprint hits (UNDR-V1-02 file-level guard)', async () => {
  const src = await readFile(FILE, 'utf8');
  // Strip code fences before scanning so language names inside fenced blocks
  // are not weighed (the persona may show shell snippets containing `make`,
  // `Coq`, etc.). The forbidden set above does NOT include those neutrals
  // anyway, but this also keeps the grep honest if patterns expand later.
  const stripped = src.replace(/```[\s\S]*?```/g, '');
  const hit = stripped.match(FORBIDDEN);
  assert.equal(hit, null, `forbidden fingerprint surfaced: ${hit && hit[0]}`);
});
