// test/state-gate-instruction.test.js
//
// Phase 7 BUILD-03 + Phase 6 carry-forward: locks the three named exports
// from lib/state-gate-instruction.js. Single source of truth for runtime
// gate prologues across all five format transforms and the persona-builder
// helper. This test pins export shape, byte-length contract, and undercover
// hygiene at the source — drift here surfaces before the format-transform
// tests catch it.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  STATE_GATE_INSTRUCTION,
  BUILD_MODE_INSTRUCTION,
  PERSONA_SECTION_SEPARATOR,
} from '../lib/state-gate-instruction.js';

const FORBIDDEN = /\b(claude|anthropic|openai|codex|copilot|gemini|aider|cline|sonnet|opus|haiku|llm|assistant)\b|\b(AI|agent)\b|cursor[ -]?ai|generated by|authored by ai/i;

test('STATE_GATE_INSTRUCTION: non-empty string, byte-length pinned to 487 (Phase 6 baseline)', () => {
  assert.equal(typeof STATE_GATE_INSTRUCTION, 'string');
  assert.ok(STATE_GATE_INSTRUCTION.length > 0);
  assert.equal(
    Buffer.byteLength(STATE_GATE_INSTRUCTION, 'utf8'),
    487,
    'STATE_GATE_INSTRUCTION byte-length drift — every existing format-transform test depends on this string being byte-equal to the v0.2.0 baseline',
  );
});

test('STATE_GATE_INSTRUCTION: starts with anchor sentence, ends with separator', () => {
  assert.ok(STATE_GATE_INSTRUCTION.startsWith('Before applying ANY rule below'));
  assert.ok(STATE_GATE_INSTRUCTION.endsWith('\n\n---\n\n'));
});

test('BUILD_MODE_INSTRUCTION: non-empty string, byte-length <= 600 (threat model T-07-02-03)', () => {
  assert.equal(typeof BUILD_MODE_INSTRUCTION, 'string');
  assert.ok(BUILD_MODE_INSTRUCTION.length > 0);
  const bytes = Buffer.byteLength(BUILD_MODE_INSTRUCTION, 'utf8');
  assert.ok(bytes <= 600, `BUILD_MODE_INSTRUCTION byte-length ${bytes} exceeds 600-char ceiling`);
});

test('BUILD_MODE_INSTRUCTION: references the catalogue file by name (discoverability)', () => {
  assert.ok(
    BUILD_MODE_INSTRUCTION.includes('skills/build-mode-overview.md'),
    'BUILD_MODE_INSTRUCTION must reference the build-mode-overview catalogue so the host can locate the full pattern set',
  );
});

test('BUILD_MODE_INSTRUCTION: ends with separator (parallel terminator to STATE_GATE_INSTRUCTION)', () => {
  assert.ok(BUILD_MODE_INSTRUCTION.endsWith('\n\n---\n\n'));
});

test('PERSONA_SECTION_SEPARATOR: contains the BUILD-MODE EXTENSIONS heading', () => {
  assert.equal(typeof PERSONA_SECTION_SEPARATOR, 'string');
  assert.ok(PERSONA_SECTION_SEPARATOR.length > 0);
  assert.ok(PERSONA_SECTION_SEPARATOR.includes('# BUILD-MODE EXTENSIONS'));
});

test('all three exports: zero forbidden-fingerprint hits (UNDR-V1-02)', () => {
  for (const [name, value] of [
    ['STATE_GATE_INSTRUCTION', STATE_GATE_INSTRUCTION],
    ['BUILD_MODE_INSTRUCTION', BUILD_MODE_INSTRUCTION],
    ['PERSONA_SECTION_SEPARATOR', PERSONA_SECTION_SEPARATOR],
  ]) {
    const hit = value.match(FORBIDDEN);
    assert.equal(hit, null, `forbidden fingerprint in ${name}: ${hit && hit[0]}`);
  }
});

// ---
// TEST-12 locked content snapshots (Phase 9 plan 06).
//
// The seven tests above pin export shape, byte-length, anchor sentences, and
// fingerprint hygiene. The three tests below pin verbatim text fragments at
// the substring level — the surface that downstream format transforms read
// when they prepend gate prologues. If any of these substrings drift, every
// shipped rule body's host-facing contract drifts with them.
//
// State-file path and engagement key (STATE_GATE_INSTRUCTION):
//   - `~/.10x-engineer/state.json` is the path the host reads at runtime.
//   - `"enabled": true` is the JSON key/value the host checks before
//     applying any rule below the gate.
//
// Build-mode keystone and trigger phrase (BUILD_MODE_INSTRUCTION):
//   - `skills/build-mode-overview.md` is the catalogue the host consults
//     when an artefact is requested.
//   - `tangible artefact` is the trigger phrase that distinguishes
//     build-mode requests from response-mode requests.
//
// Section header (PERSONA_SECTION_SEPARATOR):
//   - `BUILD-MODE EXTENSIONS` is the in-file divider written between the
//     response-mode and build-mode halves of persona.txt at install time.

test('TEST-12 locked snapshot: STATE_GATE_INSTRUCTION includes the state-file path and engagement key', () => {
  assert.ok(
    STATE_GATE_INSTRUCTION.includes('~/.10x-engineer/state.json'),
    'STATE_GATE_INSTRUCTION must reference the state file path verbatim',
  );
  assert.ok(
    STATE_GATE_INSTRUCTION.includes('"enabled": true'),
    'STATE_GATE_INSTRUCTION must reference the engagement key verbatim',
  );
});

test('TEST-12 locked snapshot: BUILD_MODE_INSTRUCTION includes the catalogue keystone and trigger phrase', () => {
  assert.ok(
    BUILD_MODE_INSTRUCTION.includes('skills/build-mode-overview.md'),
    'BUILD_MODE_INSTRUCTION must reference the build-mode catalogue verbatim',
  );
  assert.ok(
    BUILD_MODE_INSTRUCTION.includes('tangible artefact'),
    'BUILD_MODE_INSTRUCTION must contain the trigger phrase verbatim',
  );
});

test('TEST-12 locked snapshot: PERSONA_SECTION_SEPARATOR includes the BUILD-MODE EXTENSIONS header text', () => {
  assert.ok(
    PERSONA_SECTION_SEPARATOR.includes('BUILD-MODE EXTENSIONS'),
    'PERSONA_SECTION_SEPARATOR must include the section header verbatim',
  );
});
